# Kernel SVM

## Importing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('pulsar.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[ 1.33898438e+02  4.69297746e+01  3.87951750e-02 ...  1.95615370e+01
   8.57437793e+00  8.07954514e+01]
 [ 2.70390625e+01  3.37547224e+01  4.77912374e+00 ...  7.88154399e+01
  -3.48492115e-01 -8.93790697e-01]
 [ 1.07718750e+02  5.20618529e+01  2.78869299e-01 ...  4.05191430e+01
   3.34724977e+00  1.04413225e+01]
 ...
 [ 1.33164062e+02  5.54754700e+01 -9.44232330e-02 ...  1.26535027e+01
   1.21759792e+01  1.81458434e+02]
 [ 9.81718750e+01  4.88055948e+01  3.11807442e-01 ...  1.62043130e+01
   1.02032095e+01  1.22776632e+02]
 [ 1.06046875e+02  4.20750556e+01  4.21143692e-01 ...  1.99249204e+01
   7.31348277e+00  5.87921276e+01]]


In [5]:
print(y_train)

[0 1 0 ... 0 0 0]


In [6]:
print(X_test)

[[ 1.02289062e+02  4.57590757e+01  2.31697754e-01 ...  1.43430197e+01
   9.50036830e+00  1.17057724e+02]
 [ 1.20093750e+02  5.17653114e+01  1.52884958e-01 ...  1.96742682e+01
   7.96200404e+00  7.36250634e+01]
 [ 1.08820312e+02  5.80159506e+01  3.96478925e-01 ...  1.94694241e+01
   9.30173415e+00  9.46556370e+01]
 ...
 [ 1.24601562e+02  4.96176537e+01 -7.67909800e-03 ...  1.54960315e+01
   8.04710053e+00  8.64405361e+01]
 [ 1.02046875e+02  4.87905055e+01  4.52226380e-01 ...  1.39284014e+01
   9.12749945e+00  1.16023222e+02]
 [ 1.16679688e+02  4.74069704e+01  6.94263630e-02 ...  8.26920169e+01
  -1.92942742e-01 -1.87714766e+00]]


In [7]:
print(y_test)

[0 0 0 ... 0 0 0]


In [8]:
dataset.head(1)

Mean of the integrated profile  \
0                         140.5625   

    Standard deviation of the integrated profile  \
0                                      55.683782   

    Excess kurtosis of the integrated profile  \
0                                   -0.234571   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.699648                   3.199833   

    Standard deviation of the DM-SNR curve  \
0                                19.110426   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                              7.975532                      74.242225   

   target_class  
0             0

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[ 0.89035     0.05299446 -0.41627838 ... -0.35147554  0.06520135
  -0.22396846]
 [-3.24056646 -1.87170607  3.9915008  ...  2.67629293 -1.9123934
  -0.99480636]
 [-0.12169131  0.80272308 -0.19304623 ...  0.71942064 -1.09329823
  -0.88784571]
 ...
 [ 0.8619609   1.30140731 -0.54015109 ... -0.70446375  0.86343194
   0.7259099 ]
 [-0.49074965  0.32702693 -0.16241881 ... -0.52302369  0.42620276
   0.17217532]
 [-0.18632182 -0.65621566 -0.06075285 ... -0.33290731 -0.21425354
  -0.43159673]]


In [11]:
print(X_test)

[[-0.33158946 -0.11802914 -0.23690854 ... -0.61813245  0.27043057
   0.11821043]
 [ 0.35669527  0.7594023  -0.31019236 ... -0.34571518 -0.07052038
  -0.29162984]
 [-0.07910766  1.67253786 -0.0836873  ... -0.35618235  0.22640686
  -0.09318065]
 ...
 [ 0.53095604  0.44565798 -0.45949233 ... -0.55921561 -0.05166027
  -0.17070018]
 [-0.34095183  0.32482259 -0.03185071 ... -0.6393187   0.18779085
   0.10844865]
 [ 0.22471615  0.12270643 -0.38779607 ...  2.87437909 -1.87791866
  -1.00408554]]


## Training

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting

In [13]:
print(classifier.predict(sc.transform([[140.5625,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225]])))

[0]


In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4093   22]
 [  63  297]]


0.9810055865921787